"""Weather forecast and seasonal climate intelligence page."""

import streamlit as st
from app.state.session import get_current_trip


def render_weather_page() -> None:
    """Render destination climate analysis and weather observations from Weather Agent."""
    st.title("Weather & Climate Intelligence")
    st.markdown("Forecasts, precipitation probabilities, and seasonal weather hazard detection.")

    st.markdown("---")

    active_trip = get_current_trip()
    travel_state = st.session_state.get("travel_state", {})
    weather = travel_state.get("weather")

    if active_trip:
        st.subheader(f"Destination: {active_trip.destination}")
        st.caption(f"Travel Window: {active_trip.start_date} to {active_trip.end_date}")

    if not weather:
        st.info(
            "ℹ️ **No Weather Observations Yet**: Plan a trip from **New Trip** or **Conversation** to execute the multi-agent workflow and generate climatological forecasts."
        )
        return

    st.success("⛅ **Weather Agent Deliverables**")
    st.caption("⚠️ **DEMO_DATA**: Climatological estimates generated by the mock Weather Agent. Live OpenWeather API feeds will be connected in Phase 8.")

    w1, w2, w3, w4 = st.columns(4)
    with w1:
        st.metric(
            label="Temperature",
            value=f"{weather.get('temperature_celsius', 20)}°C",
            delta=f"{weather.get('temperature_fahrenheit', 68)}°F",
        )
    with w2:
        st.metric(label="Expected Condition", value=weather.get("condition", "Fair"))
    with w3:
        st.metric(label="Precipitation Risk", value=f"{weather.get('precipitation_probability', 10)}%")
    with w4:
        st.metric(label="Relative Humidity", value=f"{weather.get('humidity_percentage', 50)}%")

    st.markdown("---")
    if weather.get("warning"):
        st.warning(f"⚠️ **Advisory Notice**: {weather.get('warning')}")

    st.caption(f"Forecast Window: `{weather.get('date')}` | Location: `{weather.get('location')}` | Source: `{weather.get('source')}`")
