"""Domain data models for the Multi-Agent Travel Intelligence Platform."""

from models.travel_request import (
    TravelRequest,
    TravelerPreferences,
    TripConstraints,
    TripMetadata,
)

from models.planner import (
    NormalizedTravelRequest,
    ClarificationRequest,
    PlannerResult,
)

from models.specialized_options import (
    FlightOption,
    HotelOption,
    ActivityOption,
    WeatherObservation,
    DestinationResearch,
)

from models.budget import (
    BudgetItemCategory,
    BudgetItem,
    BudgetBreakdown,
    BudgetStatus,
    BudgetSummary,
)

from models.validation import (
    ValidationSeverity,
    ValidationIssue,
    ValidationResult,
)

from models.mcp import (
    ToolExecutionStatus,
    ToolExecutionError,
    MCPToolCall,
    MCPToolResult,
    SearchFlightsInput,
    SearchFlightsOutput,
    CompareFlightsInput,
    CompareFlightsOutput,
    GetFlightDetailsInput,
    GetFlightDetailsOutput,
    SearchHotelsInput,
    SearchHotelsOutput,
    GetHotelDetailsInput,
    GetHotelDetailsOutput,
    SearchPlacesInput,
    SearchPlacesOutput,
    CalculateRouteInput,
    CalculateRouteOutput,
    EstimateTravelTimeInput,
    EstimateTravelTimeOutput,
    GetCurrentWeatherInput,
    GetCurrentWeatherOutput,
    GetForecastInput,
    GetForecastOutput,
    GetWeatherAlertsInput,
    GetWeatherAlertsOutput,
    WebSearchInput,
    WebSearchOutput,
    FetchPageInput,
    FetchPageOutput,
    SearchNewsInput,
    SearchNewsOutput,
    GetExchangeRateInput,
    GetExchangeRateOutput,
)

__all__ = [
    "TravelRequest",
    "TravelerPreferences",
    "TripConstraints",
    "TripMetadata",
    "NormalizedTravelRequest",
    "ClarificationRequest",
    "PlannerResult",
    "FlightOption",
    "HotelOption",
    "ActivityOption",
    "WeatherObservation",
    "DestinationResearch",
    "BudgetItemCategory",
    "BudgetItem",
    "BudgetBreakdown",
    "BudgetStatus",
    "BudgetSummary",
    "ValidationSeverity",
    "ValidationIssue",
    "ValidationResult",
    "ToolExecutionStatus",
    "ToolExecutionError",
    "MCPToolCall",
    "MCPToolResult",
    "SearchFlightsInput",
    "SearchFlightsOutput",
    "CompareFlightsInput",
    "CompareFlightsOutput",
    "GetFlightDetailsInput",
    "GetFlightDetailsOutput",
    "SearchHotelsInput",
    "SearchHotelsOutput",
    "GetHotelDetailsInput",
    "GetHotelDetailsOutput",
    "SearchPlacesInput",
    "SearchPlacesOutput",
    "CalculateRouteInput",
    "CalculateRouteOutput",
    "EstimateTravelTimeInput",
    "EstimateTravelTimeOutput",
    "GetCurrentWeatherInput",
    "GetCurrentWeatherOutput",
    "GetForecastInput",
    "GetForecastOutput",
    "GetWeatherAlertsInput",
    "GetWeatherAlertsOutput",
    "WebSearchInput",
    "WebSearchOutput",
    "FetchPageInput",
    "FetchPageOutput",
    "SearchNewsInput",
    "SearchNewsOutput",
    "GetExchangeRateInput",
    "GetExchangeRateOutput",
    "SourceTrustLevel",
    "DocumentCategory",
    "DocumentMetadata",
    "DocumentChunk",
    "RAGRetrievalQuery",
    "RetrievedChunk",
    "RAGRetrievalResult",
    "sanitize_retrieved_content",
    "format_retrieved_context_defensively",
    "SourceTrustCategory",
    "classify_domain_trust",
    "ResearchFinding",
    "ConflictingClaim",
    "FreshWebResearchResult",
    "ChangeEventType",
    "ChangeEventSeverity",
    "NodeExecutionAction",
    "ChangeEvent",
    "ImpactAnalysis",
    "ItineraryVersion",
    "ReplanningAuditRecord",
]

from models.rag import (
    SourceTrustLevel,
    DocumentCategory,
    DocumentMetadata,
    DocumentChunk,
    RAGRetrievalQuery,
    RetrievedChunk,
    RAGRetrievalResult,
    sanitize_retrieved_content,
    format_retrieved_context_defensively,
)

from models.research import (
    SourceTrustCategory,
    classify_domain_trust,
    ResearchFinding,
    ConflictingClaim,
    FreshWebResearchResult,
)

from models.replanning import (
    ChangeEventType,
    ChangeEventSeverity,
    NodeExecutionAction,
    ChangeEvent,
    ImpactAnalysis,
    ItineraryVersion,
    ReplanningAuditRecord,
)

from models.approval import (
    ActionRiskLevel,
    ApprovalStatus,
    classify_action_risk,
    READ_ONLY_ACTIONS,
    HIGH_IMPACT_ACTIONS,
    ActionProposal,
    ApprovalRequest,
    ApprovalDecision,
    ActionExecutionResult,
    ApprovalAuditEvent,
)

from models.evaluation import (
    ScenarioCategory,
    CriticalFailureType,
    CriticalFailure,
    MetricScore,
    ScenarioEvaluationResult,
    LLMJudgeResult,
    EvaluationReport,
)

__all__.extend([
    "ScenarioCategory",
    "CriticalFailureType",
    "CriticalFailure",
    "MetricScore",
    "ScenarioEvaluationResult",
    "LLMJudgeResult",
    "EvaluationReport",
])

