"""Pydantic schemas for specialized travel agents (Flights, Hotels, Activities, Weather, Research)."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class FlightOption(BaseModel):
    """Structured candidate flight option generated by the Flight Agent."""

    airline: str = Field(description="Operating airline name")
    flight_number: str = Field(description="Airline flight designation code")
    departure_airport: str = Field(description="Origin airport IATA code or city")
    arrival_airport: str = Field(description="Destination airport IATA code or city")
    departure_time: str = Field(description="Scheduled departure timestamp or string")
    arrival_time: str = Field(description="Scheduled arrival timestamp or string")
    duration: str = Field(description="Total travel duration (e.g. '11h 30m')")
    stops: int = Field(default=0, ge=0, description="Number of flight layovers (0 for nonstop)")
    cabin_class: str = Field(default="Economy", description="Cabin service class")
    price: float = Field(ge=0.0, description="Total price for all travelers")
    currency: str = Field(default="USD", description="Currency 3-letter ISO code")
    source: str = Field(default="Mock Flight Catalog [DEMO_DATA]", description="Attributed data source")
    availability_status: str = Field(default="Demo Available", description="Simulated ticket availability indicator")
    demo_data: bool = Field(default=True, description="Strict marker indicating synthetic demo data")


class HotelOption(BaseModel):
    """Structured accommodation option generated by the Hotel Agent."""

    name: str = Field(description="Hotel or property name")
    location: str = Field(description="Neighborhood, district, or city area")
    rating: float = Field(default=4.0, ge=1.0, le=5.0, description="Guest rating out of 5.0")
    stars: int = Field(default=4, ge=1, le=5, description="Star classification rating")
    price_per_night: float = Field(ge=0.0, description="Nightly room charge")
    total_price: float = Field(ge=0.0, description="Total stay accommodation cost")
    currency: str = Field(default="USD", description="Currency 3-letter ISO code")
    amenities: List[str] = Field(default_factory=list, description="Included amenities and perks")
    room_type: str = Field(default="Standard Room", description="Room classification")
    source: str = Field(default="Mock Hospitality Catalog [DEMO_DATA]", description="Attributed data source")
    availability_status: str = Field(default="Demo Available", description="Simulated room availability indicator")
    demo_data: bool = Field(default=True, description="Strict marker indicating synthetic demo data")


class ActivityOption(BaseModel):
    """Structured experience or point-of-interest option curated by the Activity Agent."""

    name: str = Field(description="Experience, attraction, or tour title")
    location: str = Field(description="Specific venue, landmark, or district")
    category: str = Field(description="Activity genre (e.g. Culture, Dining, Nature, Adventure)")
    duration: str = Field(description="Estimated duration (e.g. '2-3 hours', 'Half Day')")
    estimated_cost: float = Field(default=0.0, ge=0.0, description="Cost per person or total activity entry")
    currency: str = Field(default="USD", description="Currency 3-letter ISO code")
    best_time: str = Field(default="Morning", description="Recommended time of day to visit")
    description: str = Field(description="Concise description highlighting traveler value")
    source: str = Field(default="Mock Experiences Catalog [DEMO_DATA]", description="Attributed data source")
    demo_data: bool = Field(default=True, description="Strict marker indicating synthetic demo data")


class WeatherObservation(BaseModel):
    """Structured climatological forecast context produced by the Weather Agent."""

    date: str = Field(description="Observation date or seasonal forecast window")
    location: str = Field(description="Destination city or region")
    temperature_celsius: float = Field(description="Expected temperature in Celsius")
    temperature_fahrenheit: float = Field(description="Expected temperature in Fahrenheit")
    condition: str = Field(description="General sky and weather condition (e.g. Sunny, Clear, Light Rain)")
    precipitation_probability: int = Field(default=10, ge=0, le=100, description="Probability of precipitation (%)")
    humidity_percentage: int = Field(default=50, ge=0, le=100, description="Relative humidity (%)")
    warning: Optional[str] = Field(default=None, description="Advisory weather alerts or seasonal warnings")
    source: str = Field(default="Mock Climatological Service [DEMO_DATA]", description="Attributed data source")
    demo_data: bool = Field(default=True, description="Strict marker indicating synthetic demo data")


class DestinationResearch(BaseModel):
    """Curated destination context, tips, and customs compiled by the Research Agent."""

    destination: str = Field(description="Target destination name")
    destination_overview: str = Field(description="Broad overview of the destination and character")
    cultural_notes: List[str] = Field(default_factory=list, description="Cultural insights and etiquette")
    travel_tips: List[str] = Field(default_factory=list, description="Practical logistics, transit, and safety tips")
    local_customs: List[str] = Field(default_factory=list, description="Traditional manners and social practices")
    important_notes: List[str] = Field(default_factory=list, description="Essential advisories (visas, cash vs card)")
    sources: List[str] = Field(default_factory=list, description="Source attributions")
    fresh_findings: List[Dict[str, Any]] = Field(default_factory=list, description="Fresh research findings from web search")
    conflicts: List[Dict[str, Any]] = Field(default_factory=list, description="Source discrepancies or conflicting claims")
    official_verified: bool = Field(default=False, description="True if official government/authority sources verified requirements")
    demo_data: bool = Field(default=True, description="Strict marker indicating synthetic demo data")
